server:
  # extraVolumes:
  # - type: secret
  #   name: vault-storage-config
  #   path: null

  # extraArgs: -config=/vault/userconfig/vault-storage-config/config.hcl

  ingress:
    enabled: true
    annotations: 
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - host: ${fqdn}
        paths:
          - /vault(/|$)(.*)

    tls: 
    - secretName: vault-tls
      hosts:
        - ${fqdn}

  standalone:
    enabled: "false"

  ha:
    enabled: true
    replicas: 3

    raft:
      enabled: true
# Vault UI
ui:
  enabled: true
