{{- if .Values.initvault.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.initvault.sa.name }}-sa
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.initvault.sa.name }}-role
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.initvault.sa.name }}-rb
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.initvault.sa.name }}-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.initvault.sa.name }}-sa
  namespace: {{ .Release.Namespace }}
{{- end }}
