{{- if .Values.initvault.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: initvault-unseal-job
  labels:
    app: initvault
    comp: unseal-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      volumes:
      - name: script-volume
        configMap:
          name: vault-config-sh
      containers:
      - name: {{ .Chart.Name }}
        image: alpine
        volumeMounts:
          - name: script-mount
            mountpath: /scripts/unseal.sh
            readOnly: true
        command:
          - "/bin/sh"
          - "-c"
        args:
          - |
            ls /scripts/        
        
{{- end -}}