# This will run helm post-install hook to init the vault
initvault:
  enabled: true

  sa:
    name: unseal-job

  job:
    podLabels:
  # The ldap auth related params
  ldapauth:
    enabled: false
    ldap_url: "ldap://"
    userattr: ""
    userdn: ""
    groupdn: ""
    upndomain: ""

  # The GitHub auth related params
  githubauth:
    enabled: false
    organization: ""

  # The Kubernetes auth related params
  k8sauth:
    enabled: false
    token_reviewer_jwt: ""
    kubernetes_host: ""
    kubernetes_ca_cert: ""

  # More Auth can be added here as per reqiurement

    podAnnotations:

vault:
  server:
   
    # Used to define custom readinessProbe settings
    readinessProbe:
      enabled: true
      # If you need to use a http path instead of the default exec
      path: '/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204'
